### ISSUE TITLE
RFI Details and next step

### ISSUE THREAD

**Issue by mycomport1** [ScottTilley/Artemis1#1]
Hi Scott, I'm representing two entities Reconfigurable Antenna Laboratory and Space Flight Laboratory,
University of Toronto Institute for Aerospace Studies, with respect of all your hard work and would like to cooperate on this project. Lets discuss of possible issues and ways to improve and extend existing  stations. My email in your blog. Thanks!

**Comment by ScottTilley** [comment]
Thank-you for your interest in our work. At the present time we are not seeking to add collaborators to our efforts.  You are welcome to follow our work and share publicly your results so we can consider future collaboration opportunities.  

Regards,
Scott

**Comment by mycomport1** [comment]
@Scott ***@***.***>
@ScottTilley/Artemis1

Hi Scott!
I got it. And the reasons is understandable.
I'll try my best to do my initial steps to proceed.
And it is a good plan for me, much appreciate!

Thanks a lot and all the best wishes with your Project.

Alex

________________________________
